### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by kangarooInternational** [maxlefou/hugo.386#1]
There is an typing error in /exampleSite/content/post/markdown-syntax.md in line 59.
You wrote the word supports twice.
The rest works perfectly fine for me and I really like it.

**Comment by jmfergeau** [comment]
Corrected in [59d3e71](https://github.com/maxlefou/hugo.386/commit/59d3e7102dce523cbef0106ccc7ba35793c1f080). thanks.

IT's not me who wrote the content of examplesite though. This is provided by hugo. They corrected the mistake on their end, though.
