### ISSUE TITLE
Does hugo.386 have to flash the white text www page?

### ISSUE THREAD

**Issue by Paulie420** [maxlefou/hugo.386#7]
Is there a way to mitigate this? Every time I click a page, it flashes a white text stock www page before drawing hugo.386. Also, can I make that cursor-draw feature go away?

**Comment by jmfergeau** [comment]
> it flashes a white text stock www page

You mean like if CSS didn't load? 

Then no, not really. It means your web server provider isn't fast enough. (Netlify? I noticed it does it with Netlify) Maybe if you check about how hugo uses cache features but the very first time will always be like that.

> Also, can I make that cursor-draw feature go away?

Yes. Look for these in your config.toml:
```
    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false
```
